apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
  labels:
    app: shoppingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      containers:
      - name: shoppingapi
        image: shoppingnewmanacr.azurecr.io/shoppingapi:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: DatabaseSettings__ConnectionStaring
          valueFrom:
            configMapKeyRef:
              name: mango-configmap
              key: connection_string
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: acr-secret
---

apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
spec:
  type: ClusterIP
  selector:
    app: shoppingapi
  ports:
  - port: 80
    targetPort: 8080
